version: "3.2"

services:
  keycloak_admin_ui:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak_admin_ui
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    command:
      - "start-dev"
      - --import-realm
    volumes:
      - ./target/keycloak-token-status-plugin-1.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-token-status-plugin-1.0.0-SNAPSHOT.jar
    depends_on:
      - keycloakdb
    ports:
      - '9090:8081'
    networks:
      - backend
      
  keycloakdb:
    image: postgres:15
    container_name: keycloakdb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  keycloak_data:

networks:
  backend:
    driver: bridge