package com.adorsys.keycloakstatuslist.jpa.entity;

import jakarta.persistence.*;

import java.util.Objects;

@Entity
@Access(AccessType.FIELD)
@Table(name = "status_list_mapping", indexes = {
        @Index(name = "idx_status_list_token", columnList = "token_id")
})
public class StatusListMappingEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", length = 36)
    private String id;

    // The business index generated by the database sequence
    // TODO: Fix auto-increment on the field
    // @Column(name = "idx", nullable = false)
    // @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "status_list_seq_gen")
    // @SequenceGenerator(name = "status_list_seq_gen", sequenceName = "status_list_counter_seq", allocationSize = 1)
    @Column(name = "idx", nullable = false, updatable = false, insertable = false, columnDefinition = "BIGSERIAL")

    private Long idx;

    @Column(name = "status_list_id", nullable = false)
    private String statusListId;

    @Column(name = "user_id")
    private String userId;

    @Column(name = "token_id")
    private String tokenId;

    @Column(name = "realm_id")
    private String realmId;

    // --- Getters and Setters ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Long getIdx() {
        return idx;
    }

    public void setIdx(Long idx) {
        this.idx = idx;
    }

    public String getStatusListId() {
        return statusListId;
    }

    public void setStatusListId(String statusListId) {
        this.statusListId = statusListId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTokenId() {
        return tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    public String getRealmId() {
        return realmId;
    }

    public void setRealmId(String realmId) {
        this.realmId = realmId;
    }

    @Override
    public final boolean equals(Object o) {
        if (!(o instanceof StatusListMappingEntity that)) return false;

        return Objects.equals(getId(), that.getId()) && Objects.equals(getIdx(), that.getIdx()) && Objects.equals(getStatusListId(), that.getStatusListId()) && Objects.equals(getUserId(), that.getUserId()) && Objects.equals(getTokenId(), that.getTokenId()) && Objects.equals(getRealmId(), that.getRealmId());
    }

    @Override
    public int hashCode() {
        int result = Objects.hashCode(getId());
        result = 31 * result + Objects.hashCode(getIdx());
        result = 31 * result + Objects.hashCode(getStatusListId());
        result = 31 * result + Objects.hashCode(getUserId());
        result = 31 * result + Objects.hashCode(getTokenId());
        result = 31 * result + Objects.hashCode(getRealmId());
        return result;
    }
}